### ISSUE TITLE
[Question] How can I get stealthaddress of bitcoin

### ISSUE THREAD

**Issue by ghost** [vergecurrency/BitcoinKit#3]
I have searched all the source code of bitcoin and couldn't find 0x2A and 0x2B.

**Comment by justinvforvendetta** [comment]
bitcoin does not offer stealth addresses.

**Comment by marpme** [comment]
https://github.com/vergecurrency/BitcoinKit/blob/5bbb16d1b4c457f6568faeb58379a964b9b0505d/Sources/BitcoinKit/Core/Keys/Address.swift#L225-L310

**Comment by ghost** [comment]
Thanks! But I still have some issues about the 0x2A in mainnet and 0x2B in testnet. Is this two coded in bitcoin's core or it's just a random byte you defined?

**Comment by marpme** [comment]
Actually it's just: 

```cpp
const uint8_t stealth_version_byte = 0x28;
```
It just represents the version of the stealth addressing and it's mostly random

**Comment by justinvforvendetta** [comment]
selected randomly when creating stealth support in the verge core source code

**Comment by ghost** [comment]
Got it! Thank you guys so much for helping me :D
